### PR TITLE
Allow render.py to remember the first letter of the author

### PR DESCRIPTION
**Pull request by l0010o0001l**
Meepses. https://github.com/tildetown/tilde-rfcs/issues/1

### CODE REVIEW

**Comment by MineRobber9000** [comment]
Have you tested it?

**Comment by l0010o0001l** [comment]
Yessum @MineRobber9000!

**Comment by MineRobber9000** [comment]
Alright! Good job @l0010o0001l!

**Comment by l0010o0001l** [comment]
i luv u @MineRobber9000

**Pull request merged**
